server:
  port: 9000

logging:
  config: classpath:config/logback/logback-spring.xml


spring:
  profiles:
    active: ${profileActive}
  jackson:
    propertyNamingStrategy: SNAKE_CASE
  application:
    name: learning-feign-provider

  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.ip-address}:${server.port}
        ip-address: 127.0.0.1
        health-check-path: /endpoint/_common/_health
        health-check-critical-timeout: 10s
        health-check-interval: 3s