package map_r
import java.util.Map
import com.weweibuy.webuy.learning.drools.uils.ListUtils

rule "map_r"
    when
        $map:Map(age > 12 &&  ListUtils.containsAll(["1","2","3"],["1","3"]))
    then
        $map.put("name", "tom");
        $map.put("list", ListUtils.stringToList("2,3,4,5,6"));

        System.err.println("age 是: " + $map.get("age"));
end


rule "map_r1"
    when
        $map:Map(tax.income > 3500)
    then
        System.err.println("收入大于3500");
 end

 rule "map_r2"
     when
         $map:Map(map != null)
     then
     Object map = $map.get("map");
     ((Map)map).put("namei", "xxx");
     System.err.println("map map");
end

rule "map_r3"
    when
        $map:Map(age memberOf ["12","13"])
    then
        System.err.println("memberOf");
end
