server:
  port: 8070
  tomcat:
    max-threads: 10
    min-spare-threads: 5    #初始化线程数
  session:
    store-type: REDIS
  servlet:
    session:
      timeout: 600


security:
   oauth2:
     client:
       client-id: webuy
       client-secret: webuy123
spring:
  session:
    redis:
      flush-mode:




